name: Ruff
on:
  pull_request:
  push:
    branches: [main]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install ruff
      # Fail if formatting is needed:
      - run: ruff format --check .
      # Fail on lint errors (no auto-fix in CI):
      # - run: ruff check .
